### ISSUE TITLE
assemble to disk doesn't seem to work

### ISSUE THREAD

**Issue by estokes** [dansanderson/easyasm65#1]
Using v0.1 from the file host,

I type in the "SIMPLE.S" example program from readme.md, it runs just fine with assemble and test, and when I assemble to disk it does produce a file "SIMPLE" of type PRG. However when I switch out of edit mode and run that program I get "syntax error in line 1000". 

When I load the "SIMPLE" PRG file that was generated and list it, it is just the source code for the assembly program, not the expected SYS call basic header followed by the assembled code.

When I load the file using the monitor, the result is the same.

**Comment by oe4dns** [comment]
Same here, though I hav only tested with Xemu yet. I will try on real hardware too and report.

**Comment by oe4dns** [comment]
Can confirm, same issue on a real Mega65 R3

**Comment by oe4dns** [comment]
Did another Test - it works with  the current Beta (v 920407) ROM, but nut the current release (v 920395)

**Comment by estokes** [comment]
Ah, I was wondering about that. I'll just upgrade then. I guess this PR will be useful to anyone else who has the same problem.

**Comment by dansanderson** [comment]
Mentioned in the forum but I'll echo this here, thanks for the report! EasyAsm uses the extended SETBNK feature introduced in a recent ROM beta that will be in the next stable release v0.97 coming soon. I'm not sure it'll be worth adding a workaround for the v0.96 ROM given the release schedule, so I'll just add this to the README for now.
