### ISSUE TITLE
Function RUN "XXXX"

### ISSUE THREAD

**Issue by Josefino** [dansanderson/easyasm65#3]
I tried program BRK, everything works as it should in EDIT ON mode. If I run the compiled PRG on disk with the RUN "BRK" command it reports an error on the very first line, because the program tries to run as a regular Basic program.
SAVING @:BRK

# ASSEMBLE TO DISK COMPLETE

OK.
EDIT OFF

READY.
RUN "BRK"

LOADING 0:BRK

?SYNTAX ERROR IN 1000
READY.
LIST

1000 !TO "BRK", RUNNABLE
1010 INC $D020
1020 BRK
1030 DEC $D020
1040 RTS
READY.

**Comment by dansanderson** [comment]
Try using the latest ROM beta 920408. EasyAsm uses a file saving feature that was introduced in a ROM newer than the latest stable release. Without this feature, it will accidentally save bytes from the source file as the binary file when assembling to disk. I forgot to document this initially. Apologies for the inconvenience!

**Comment by Josefino** [comment]
Thank you very much. I have prepared a new MEGA65.ROM, and now it works properly. Josef
