### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pchnl** [dansanderson/easyasm65#6]
Terrific project that I am currently trying out. I hope to learn some assembler using EasyAsm and the build-in monitor tools of the MEGA65. I am totally new to the C64/MEGA65 world. 
 Thanks!

**Comment by pchnl** [comment]
Please delete this entry, created in error.

**Comment by dansanderson** [comment]
Glad you're enjoying EasyAsm! You may have discovered this already but you should be able to assemble to U9 by setting the default DOS device: `SET DEF 9` Let me know if you encounter any issues, I don't recall doing much testing on that.
